version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27
workflows:

  deploy:
    jobs:
      - orb-tools/publish:
          name: publish-dev
          orb-path: orb.yml
          orb-ref: christeredvartsen/persist-env@dev:${CIRCLE_BRANCH}
          publish-token-variable: ORB_PUBLISHING_TOKEN
          validate: true
          filters:
            tags:
              ignore: /.*/
      - orb-tools/publish:
          name: publish-prod
          orb-path: orb.yml
          orb-ref: christeredvartsen/persist-env@${CIRCLE_TAG}
          publish-token-variable: ORB_PUBLISHING_TOKEN
          validate: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
